version: "3.7"
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ${LOCAL_DATA_DIR}:/meteringdata
      - ${SRC_ROOT}:/var/www/html/
      - ./conf/plugins:/var/www/html/conf/plugins
      - phpsocket:/var/run/php

volumes:
  phpsocket:
