version: "3.7"
services:
  db_postgresql:
    build:
      context: ./docker/postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php
    networks:
      - backend
    volumes:
      - ${SRC_ROOT}/logs/php:/logs
      - ${SRC_ROOT}:/var/www/html/
      - phpsocket:/var/run/php
    depends_on:
      - db_postgresql
    container_name: "dareffort_php"
    environment:
      - VIRTUAL_HOST=dareffort.s4.srg.hu


  apache:
    build:
      context: ./docker/apache
    depends_on:
      - php
      - db_postgresql
    networks:
      - backend
      - frontend
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${SRC_ROOT}/logs/apache:/logs
      - ${SRC_ROOT}:/var/www/html
      - phpsocket:/var/run/php
    environment:
      - VIRTUAL_HOST=dareffort.s4.srg.hu

volumes:
  phpsocket:
  postgres_data:
networks:
  backend:
  frontend:
