version: "3.7"
services:
  data_php:
    build:
      context: ./data_php
    volumes:
      - ../${LOCAL_DATA_DIR}:/meteringdata
      - ../${SRC_ROOT}:/var/www/html/
      - ../conf/plugins:/var/www/html/conf/plugins
    command: tail -f /dev/null
#    network_mode: host
#    environment:
#      - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=On
