version: "3.7"
services:
  data_php:
    build:
      context: ./data_php
    volumes:
      - ../${LOCAL_DATA_DIR-}:/meteringdata:ro
      - ../${SRC_ROOT-src}:/var/www/html/
      - ../conf/plugins:/var/www/html/conf/plugins
    command: tail -f /dev/null
    user: ${CURRENT_UID}
