version: "3.7"
services:
  dist_database:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER-environet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-q3DW7Ptb}
      POSTGRES_DB: ${POSTGRES_DB-environet}
    networks:
      - backend
    ports:
      - ${DB_HOST_PORT-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dist_php:
    build:
      context: ./php
    networks:
      - backend
    volumes:
      - ../${SRC_ROOT-src}/logs/php:/logs
      - ../${SRC_ROOT-src}:/var/www/html/

      - phpsocket:/var/run/php
    depends_on:
      - dist_database

  dist_apache:
    build:
      context: ./apache
    depends_on:
      - dist_php
      - dist_database
    networks:
      - backend
      - frontend
    ports:
      - ${HOST_PORT-80}:80
    volumes:
      - ../${SRC_ROOT-src}/logs/apache:/logs
      - ../${SRC_ROOT-src}:/var/www/html
      - phpsocket:/var/run/php

volumes:
  phpsocket:
  postgres_data:
networks:
  backend:
  frontend:
