version: "3.7"
services:
  dist_database:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    ports:
      - ${DB_HOST_PORT-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dist_php:
    build:
      context: ./php
    networks:
      - backend
    volumes:
      - ../${SRC_ROOT}/logs/php:/logs
      - ../${SRC_ROOT}:/var/www/html/
      - phpsocket:/var/run/php
    depends_on:
      - dist_database

  dist_apache:
    build:
      context: ./apache
    depends_on:
      - dist_php
      - dist_database
    networks:
      - backend
      - frontend
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ../${SRC_ROOT}/logs/apache:/logs
      - ../${SRC_ROOT}:/var/www/html
      - phpsocket:/var/run/php

volumes:
  phpsocket:
  postgres_data:
networks:
  backend:
  frontend:
